@echo off
cd /d "%~dp0"
if exist ".venv\Scripts\activate.bat" call ".venv\Scripts\activate.bat"
set STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
set STREAMLIT_SERVER_RUN_ON_SAVE=false
set STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
set TMG_LOCAL_PERFORMANCE=1
set TMG_UPLOAD_LIMIT_MB=8000
set TMG_PREVIEW_MAX_DIM=11000
set TMG_PREVIEW_JPEG_QUALITY=97
set TMG_PREVIEW_MIN_JPEG_QUALITY=92
set TMG_PREVIEW_MAX_PAYLOAD_MB=80
set TMG_PREVIEW_MIN_DIM=5200
set TMG_CONTAGEM_PREVIEW_MAX_DIM=10000
set TMG_CONTAGEM_PREVIEW_JPEG_QUALITY=98
set TMG_CONTAGEM_PREVIEW_MIN_JPEG_QUALITY=92
set TMG_CONTAGEM_PREVIEW_MAX_PAYLOAD_MB=64
set TMG_CONTAGEM_PREVIEW_MIN_DIM=5600
set TMG_ORTHO_DISK_CACHE_FILES=96
set TMG_ORTHO_DISK_CACHE_GB=5
set TMG_SESSION_ORTHO_CACHE_ITEMS=3
python -m streamlit run "tmg_app_final.py" --server.address localhost --server.port 8501 --server.headless=false --browser.gatherUsageStats=false
pause
